<?php
declare(strict_types=1);

/**
 * Generated by scripts/build_exam_home_highlights_index.php.
 * Do not edit manually; run the generator after catalog changes.
 */
function dent_exams_home_highlights_index(): array
{
    return array (
  'schemaVersion' => 1,
  'sourceSignature' => 'eb16f7ba2fe1f95a09adc402e9ab69369019300348be8a1ed829a20894dda658',
  'defaultCatalogKey' => 'shared',
  'catalogByCohort' => 
  array (
    'dentistry-1402' => 'shared',
    'dentistry-1403' => 'shared',
    'dentistry-1404' => 'shared',
    'prosthesis-1402' => 'shared',
    'site-users' => 'shared',
  ),
  'catalogs' => 
  array (
    'shared' => 
    array (
      0 => 
      array (
        'catalogKey' => 'shared',
        'slug' => 'medical-emergencies-term6-final-sample',
        'title' => 'آزمون نمونه سوالات پایان‌ترم فوریت پزشکی',
        'shortTitle' => 'نمونه سوالات فوریت پزشکی',
        'cardDescription' => 'سه آزمون نمونه سوال فوریت پزشکی شامل ۸۵ سؤال چهارگزینه‌ای با پاسخ تشریحی، کلید سال‌های اخیر، منبع و تحلیل گزینه‌ها.',
        'heroDescription' => 'این مجموعه شامل سه آزمون فوریت پزشکی با مجموع ۸۵ سؤال چهارگزینه‌ای است. پاسخنامه‌ها با بخش پیش‌بینی از کلیدهای سال‌های اخیر، منبع و تحلیل گزینه‌ها تکمیل شده‌اند. با یک بار پرداخت ۴۵ هزار تومان، هر سه آزمون برای همین حساب فعال می‌شوند.',
        'addedAt' => '2026-08-23T22:01:11+03:30',
        'path' => '/exams/medical-emergencies-term6-final-sample/',
        'stats' => 
        array (
          'examCount' => 3,
        ),
        'curriculum' => 
        array (
          'finalExam' => 
          array (
            'expiresAt' => '2026-08-25T00:00:00+03:30',
          ),
        ),
      ),
      1 => 
      array (
        'catalogKey' => 'shared',
        'slug' => 'dental-materials-foundations-final-sample',
        'title' => 'آزمون نمونه سوالات پایان‌ترم مبانی مواد دندانی',
        'shortTitle' => 'نمونه سوالات پایان‌ترم مواد دندانی',
        'cardDescription' => 'دو آزمون نمونه سوال پایان‌ترم مبانی مواد دندانی شامل ۷۲ سؤال تستی و ۱۶ سؤال تشریحی با پاسخ کامل.',
        'heroDescription' => 'این مجموعه مربوط به درس آزمون نمونه سوالات پایان‌ترم مبانی مواد دندانی ترم ۶ است و فعلاً ۲ آزمون با مجموع ۸۸ سوال را پوشش می‌دهد. با یک بار پرداخت ۴۵ هزار تومان، کل درس برای همین حساب فعال می‌شود.',
        'addedAt' => '2026-08-20T21:30:00+03:30',
        'path' => '/exams/dental-materials-foundations-final-sample/',
        'stats' => 
        array (
          'examCount' => 2,
        ),
        'curriculum' => 
        array (
          'finalExam' => 
          array (
            'expiresAt' => '2026-08-23T00:00:00+03:30',
          ),
        ),
      ),
    ),
  ),
);
}
